# 生产环境 Docker Compose 配置
# 包含 Nginx 反向代理和 SSL 支持

version: '3.8'

services:
  # Telegram Bot 和 Web 服务
  telegram-album-bot:
    build: .
    container_name: telegram-album-bot
    restart: unless-stopped
    expose:
      - "5000"
    volumes:
      - ./data:/app/data
      - ./qrcodes:/app/qrcodes
    env_file:
      - .env
    environment:
      - TZ=Asia/Shanghai
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:5000/health')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: telegram-album-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro  # SSL 证书目录
    depends_on:
      - telegram-album-bot
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "2"

networks:
  app-network:
    driver: bridge


